# 1000imagesのEDA

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2

path = '/Users/kaise/Desktop/job/KaiTech/medical-guideline-project/x-ray/raw_data/1000images'

df = pd.read_csv(os.path.join(path, 'labels_subset_1000.csv'))

df.head()

,Image Index,Finding Labels,Follow-up #,Patient ID,Patient Age,Patient Gender,View Position,OriginalImage[Width,Height],OriginalImagePixelSpacing[x,...,Mass,Pneumothorax,Consolidation,Pleural_Thickening,Cardiomegaly,Emphysema,Edema,Fibrosis,Pneumonia,Hernia
0,00000013_024.png,Mass,24,13,57,M,AP,2500,2048,0.168,...,1,0,0,0,0,0,0,0,0,0
1,00000061_012.png,Edema|Effusion|Infiltration|Pleural_Thickening...,12,61,77,M,AP,3056,2544,0.139,...,0,0,0,1,0,0,1,0,1,0
2,00000103_008.png,Mass,8,103,60,M,PA,2634,2649,0.143,...,1,0,0,0,0,0,0,0,0,0
3,00000113_001.png,Atelectasis|Cardiomegaly|Effusion,1,113,73,M,PA,2992,2991,0.143,...,0,0,0,0,1,0,0,0,0,0
4,00000143_004.png,No Finding,4,143,90,M,PA,2558,2991,0.143,...,0,0,0,0,0,0,0,0,0,0

In [8]:
# 全てのカラムを表示
pd.set_option('display.max_columns', None)
df.head()

,Image Index,Finding Labels,Follow-up #,Patient ID,Patient Age,Patient Gender,View Position,OriginalImage[Width,Height],OriginalImagePixelSpacing[x,y],Unnamed: 11,labels_list,No Finding,Infiltration,Effusion,Atelectasis,Nodule,Mass,Pneumothorax,Consolidation,Pleural_Thickening,Cardiomegaly,Emphysema,Edema,Fibrosis,Pneumonia,Hernia
0,00000013_024.png,Mass,24,13,57,M,AP,2500,2048,0.168,0.168,NaN,['Mass'],0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
1,00000061_012.png,Edema|Effusion|Infiltration|Pleural_Thickening...,12,61,77,M,AP,3056,2544,0.139,0.139,NaN,"['Edema', 'Effusion', 'Infiltration', 'Pleural...",0,1,1,0,0,0,0,0,1,0,0,1,0,1,0
2,00000103_008.png,Mass,8,103,60,M,PA,2634,2649,0.143,0.143,NaN,['Mass'],0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
3,00000113_001.png,Atelectasis|Cardiomegaly|Effusion,1,113,73,M,PA,2992,2991,0.143,0.143,NaN,"['Atelectasis', 'Cardiomegaly', 'Effusion']",0,0,1,1,0,0,0,0,0,1,0,0,0,0,0
4,00000143_004.png,No Finding,4,143,90,M,PA,2558,2991,0.143,0.143,NaN,['No Finding'],1,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [9]:
# View Position の分布
df['View Position'].value_counts()

View Position
PA    565
AP    435
Name: count, dtype: int64

In [12]:
# Patient ID のunique数
print("Patient ID のunique数: ", len(df['Patient ID'].unique()))
# 最大何枚あるか
df['Patient ID'].value_counts().max()

Patient ID のunique数:  893

np.int64(5)